### ISSUE TITLE
Whitespace in GCP files leads to dropping some points

### ISSUE THREAD

**Issue by MattiasTancred** [posm/posm-gcpi#41] opened 2018-05-04 05:53 UTC
Hi, I am trying to create a gcp_list_noimg file (does the name have to be _noimg or can it just be gcp_list?) and I am having some issues.

1.The interface will not load the file/show the points. 

EPSG:32633
gcp01 592836 6582077 62.396884
gcp02 592844 6582090 62.277474
gcp03 592839 6582058 65.513986
gcp04 592860 6582022 70.642407
gcp05 592880 6582051 68.319541
gcp06 592866 6582075 65.551683

2. The interface will accept/load the file but not project/show the points.

WGS84 UTM33N
gcp01 592836 6582077 62.396884
gcp02 592844 6582090 62.277474
gcp03 592839 6582058 65.513986
gcp04 592860 6582022 70.642407
gcp05 592880 6582051 68.319541
gcp06 592866 6582075 65.551683

3.The interface will load and show the points, **but only display gcp01 and gcp03. ??**

+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
gcp01 592836 6582077 62.396884
gcp02 592844 6582090 62.277474
gcp03 592839 6582058 65.513986
gcp04 592860 6582022 70.642407
gcp05 592880 6582051 68.319541
gcp06 592866 6582075 65.551683

4.The interface will load and show all the points correctly,  but z = 0?

+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
gcp01 592836 6582077 0
gcp02 592844 6582090 0
gcp03 592839 6582058 0
gcp04 592860 6582022 0
gcp05 592880 6582051 0
gcp06 592866 6582075 0

Can you not assign z to the gcp_list (gcp_list_noimg) ? Or am I missing/not understanding something?

//Mattias

**Comment by MattiasTancred** [comment] 2018-05-04 12:32
Hi, 

Firefox 59.0.3
Windows 10 Pro

**Comment by smathermather** [comment] 2018-05-04 16:14
Interesting. I'm not seeing this issue in 59.0.2. I'll update and check 59.0.3.

Just to be clear -- only two GCPs are loading when you have non-zero Z values? Or are they somehow missing once you associated them with a position on an image.

**Comment by smathermather** [comment] 2018-05-04 16:16
I'm seeing all the points with 59.0.3 as well. Can you show some step-by-step screen shots? Maybe I'm doing something differently.

**Comment by MattiasTancred** [comment] 2018-05-07 13:16
Hi again, 

I had some problems with my startup command so I needed to erase and pull a new clone from GIT. This solved the problem I had before.....

But I have ran in to another problem/s. 

WGS84 UTM 33N
gcp01 592588 6582118 66.854498
gcp02 592603 6582165 66.213559
gcp03 592584 6582148 66.338905
gcp04 592590 6582195 65.781954	

+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs	
gcp01 592588 6582118 66.854498
gcp02 592603 6582165 66.213559
gcp03 592584 6582148 66.338905
gcp04 592590 6582195 65.781954	

I can not project the the point gcp04, I have tried in Firefox and Chrome. 

Can you try and see if you have the same problem.

**Comment by ebrelsford** [comment] 2018-05-07 15:28
@MattiasTancred Both of these work fine for me, can you please ensure that you're using the latest build and have run `npm install` to grab the latest requirements?

Do you mean you are only seeing `gcp01`, `gcp02`, and `gcp03`? When I load either file I see all four points:

![selection_004](https://user-images.githubusercontent.com/375002/39710049-37732944-520b-11e8-9e2d-e601fa00c077.png)

**Comment by MattiasTancred** [comment] 2018-05-07 16:40
@ebrelsford that is correct. GCP04 will not show up in my map. Only gcp01, gcp02 and gcp03.

I ran ./webodm.sh update. I think something is corrupted. What would be my next move?

$ ./webodm.sh update
Updating WebODM...
git pull origin master
From https://github.com/OpenDroneMap/WebODM
 * branch            master     -> FETCH_HEAD
Already up-to-date.
docker pull opendronemap/node-opendronemap
Using default tag: latest
latest: Pulling from opendronemap/node-opendronemap
Digest: sha256:7f3e776e2b35650ef599f01f1c72e0a2fb4ad4f69e5c43dd0aca099198404f7a
Status: Image is up to date for opendronemap/node-opendronemap:latest
docker pull opendronemap/webodm_db
Using default tag: latest
latest: Pulling from opendronemap/webodm_db
Digest: sha256:437e8772fddeb7e740fe38ca8213eaee6b05584104efc6c75eb26f9f7da1da9d
Status: Image is up to date for opendronemap/webodm_db:latest
docker pull opendronemap/webodm_webapp
Using default tag: latest
latest: Pulling from opendronemap/webodm_webapp
4176fe04cefe: Already exists
851356ecf618: Already exists
6115379c7b49: Already exists
aaf7d781d601: Already exists
40cf661a3cc4: Already exists
975fe2fd635f: Already exists
bf4db784e7fd: Already exists
0491f7e9426b: Already exists
eabb8cfbe339: Already exists
c5115b6e7501: Already exists
944498c03376: Already exists
ebe1729787bb: Already exists
869782a4c80a: Already exists
66a5468e09ff: Already exists
3dd9e8230892: Already exists
8a0988826b29: Already exists
8e2ba4a46e5d: Already exists
65bcf0a9d200: Already exists
a33010a307e3: Pull complete
0dfcfa1dc4a2: Pull complete
3d48deafedb6: Pull complete
94a1d41d7f6f: Pull complete
85160df7e447: Pull complete
c8d2ed2afd61: Pull complete
Digest: sha256:57bee83e688f772395383d3183e855dfc3734dd5acdf26c20ecc50f485b350e8
Status: Downloaded newer image for opendronemap/webodm_webapp:latest
docker-compose down --remove-orphans
Stopping webapp ... done
Stopping worker ... done
Stopping db     ... done
Stopping broker ... done
Removing orphan container "node-odm-1"
Removing webapp ... done
Removing worker ... done
Removing db     ... done
Removing broker ... done
Removing network webodm_default
Done! You can now start WebODM by running ./webodm.sh start

mt022@MATTIAS1712 MINGW64 ~/webodm/webodm (master)
$ ./webodm.sh start
Checking for docker...   OK
Checking for git...   OK
Checking for python...   OK
Checking for pip...   OK
Checking for docker-compose...   OK
Starting WebODM...

Using the following environment:
================================
Host: localhost
Port: 8000
Media directory: appmedia
SSL: NO
SSL key:
SSL certificate:
SSL insecure port redirect: 80
Celery Broker: redis://broker
================================
Make sure to issue a ./webodm.sh down if you decide to change the environment.

docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml start || docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up
Starting db         ... done
Starting node-odm-1 ... done
Starting broker     ... done
Starting worker     ... done
Starting webapp     ... done
ERROR: No containers to start
Creating network "webodm_default" with the default driver
Creating db         ... done
Creating broker     ... done
Creating node-odm-1 ... done
Creating worker     ... done
Creating webapp     ... done
Attaching to db, broker, node-odm-1, worker, webapp
db            | LOG:  database system was shut down at 2018-05-07 16:17:28 UTC
db            | LOG:  MultiXact member wraparound protections are now enabled
broker        | 1:C 07 May 16:17:47.632 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker        | 1:C 07 May 16:17:47.632 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
broker        | 1:C 07 May 16:17:47.632 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
node-odm-1    | info: No tasks dump found
broker        | 1:M 07 May 16:17:47.633 * Running mode=standalone, port=6379.
broker        | 1:M 07 May 16:17:47.633 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
worker        | Postgres is up - executing command
node-odm-1    | info: Checking for orphaned directories to be removed...
worker        | wait-for-it.sh: waiting 15 seconds for broker:6379
worker        | wait-for-it.sh: broker:6379 is available after 0 seconds
worker        | Checking for celery...   OK
webapp        | Postgres is up - executing command
webapp        | wait-for-it.sh: waiting 15 seconds for broker:6379
webapp        | wait-for-it.sh: broker:6379 is available after 0 seconds
webapp        |
webapp        |  _       __     __    ____  ____  __  ___
webapp        | | |     / /__  / /_  / __ \/ __ \/  |/  /
webapp        | | | /| / / _ \/ __ \/ / / / / / / /|_/ /
webapp        | | |/ |/ /  __/ /_/ / /_/ / /_/ / /  / /
webapp        | |__/|__/\___/_.___/\____/_____/_/  /_/
webapp        |
webapp        |
webapp        | Checking python version... 3.x, good!
webapp        | Checking GDAL version... GDAL 2.2.4, released 2018/03/19, excellent!
webapp        | Running migrations
worker        | Starting worker using broker at redis://broker
worker        | INFO Initializing GRASS engine using /usr/bin/grass74
webapp        | Generated secret key
webapp        | INFO Initializing GRASS engine using /usr/bin/grass74
webapp        | INFO Booting WebODM 0.5.2
webapp        | INFO Registered [plugins.osm-quickedit.plugin]
webapp        | INFO Registered [plugins.measure.plugin]
webapp        | INFO Running npm install for posm-gcpi
webapp        | npm notice created a lockfile as package-lock.json. You should commit this file.
webapp        | npm WARN posm-gcpi@1.0.0 No description
webapp        | npm WARN posm-gcpi@1.0.0 No repository field.
webapp        |
webapp        | added 1 package in 5.857s
webapp        | INFO Registered [plugins.posm-gcpi.plugin]
webapp        | Operations to perform:
webapp        |   Apply all migrations: admin, app, auth, contenttypes, guardian, nodeodm, sessions
webapp        | Running migrations:
webapp        |   No migrations to apply.
webapp        | INFO Initializing GRASS engine using /usr/bin/grass74
webapp        | Checking for celery...   OK
webapp        | Scheduler has shutdown.
webapp        | Generating nginx configurations from templates...
webapp        | - nginx/nginx-ssl.conf
webapp        | - nginx/nginx.conf
webapp        | celery beat v4.1.0 (latentcall) is starting.
webapp        | [2018-05-07 16:18:02 +0000] [124] [INFO] Starting gunicorn 19.7.1
webapp        | [2018-05-07 16:18:02 +0000] [124] [INFO] Listening at: unix:/tmp/gunicorn.sock (124)
webapp        | [2018-05-07 16:18:02 +0000] [124] [INFO] Using worker: sync
webapp        | [2018-05-07 16:18:02 +0000] [133] [INFO] Booting worker with pid: 133
webapp        | INFO Initializing GRASS engine using /usr/bin/grass74
webapp        | __    -    ... __   -        _
webapp        | LocalTime -> 2018-05-07 16:18:02
webapp        | Configuration ->
webapp        |     . broker -> redis://broker:6379//
webapp        |     . loader -> celery.loaders.app.AppLoader
webapp        |     . scheduler -> celery.beat.PersistentScheduler
webapp        |     . db -> celerybeat-schedule
webapp        |     . logfile -> [stderr]@%WARNING
webapp        |     . maxinterval -> 5.00 minutes (300s)
webapp        | INFO Initializing GRASS engine using /usr/bin/grass74
webapp        |
webapp        |
webapp        | Congratulations! └@(･◡･)@┐
webapp        | ==========================
webapp        |
webapp        | If there are no errors, WebODM should be up and running!
webapp        |
webapp        | Open a web browser and navigate to http://localhost:8000
webapp        |
webapp        | NOTE: Windows users using docker should replace localhost with the IP of their docker machine's IP. To find what that is, run: docker-machine ip
webapp        | INFO Booting WebODM 0.5.2
webapp        | INFO Registered [plugins.osm-quickedit.plugin]
webapp        | INFO Registered [plugins.measure.plugin]
webapp        | INFO Registered [plugins.posm-gcpi.plugin]
webapp        | WARNING Session data corrupted
webapp        | WARNING Session data corrupted
webapp        | WARNING Session data corrupted
webapp        | WARNING Session data corrupted
webapp        | WARNING Session data corrupted
webapp        | WARNING Session data corrupted

**Comment by ebrelsford** [comment] 2018-05-07 17:06
Oh okay, that's useful to know. I'm using `posm-gcpi` directly from it this repo and the files you have posted work fine.

@pierotofy / @smathermather are either of you able to speak to how recent the version of `posm-gcpi` is in WebODM? It might help to include how recent it is in WebODM somehow so this doesn't get too confusing?

**Comment by pierotofy** [comment] 2018-05-07 17:25
@MattiasTancred you can ignore the session data corrupted message. It's related to an expired Django security token, which happens when you update WebODM.

**Comment by ebrelsford** [comment] 2018-05-07 17:37
Okay. I'm not sure how is best to settle this, then, since it's working fine from here?

**Comment by MattiasTancred** [comment] 2018-05-07 17:44
:) I will try some more and see what will happen. 

I have just uploaded 4 more gcp_list and all work just fine. Its just the one posted above that I am having trouble with......the gcp01. Strange...

![gcp_1_1](https://user-images.githubusercontent.com/34106285/39715831-cbb77af6-522e-11e8-9f64-5b80706c7fb2.jpg)
![gcp_1_2](https://user-images.githubusercontent.com/34106285/39715835-d07b5bac-522e-11e8-8cab-95ac295a86f1.jpg)

**Comment by ebrelsford** [comment] 2018-05-07 17:53
Okay thanks for checking. I could try installing WebODM to see what's going on.

**Comment by MattiasTancred** [comment] 2018-05-07 18:12
![gcp_1_3](https://user-images.githubusercontent.com/34106285/39717191-d0b1c094-5232-11e8-9205-babee50a0b34.jpg)

And still the interface is not "accepting" my z-values from the gcp_list. As you can see - the z = 0 in the export file.

**Comment by ebrelsford** [comment] 2018-05-09 21:48
Let's keep the z-values issue separate (#45).

@MattiasTancred: I'm looking at GCPi in WebODM with the file you're using above, but all four points are appearing as expected:

![selection_006](https://user-images.githubusercontent.com/375002/39841464-57dbe72a-53d2-11e8-808b-1b07be2a2a2f.png)

If you're definitely using the latest WebODM/GCPi, is there any chance you can post the exact file (not just the text, but the file as you're creating it)?

**Comment by ebrelsford** [comment] 2018-05-09 23:55
@MattiasTancred Thanks a lot for that, it helped me find a few issues--one being that it was a Windows-encoded file, the other being that some spaces at the ends of lines was causing this unexpected behavior.

I pushed a fix to master and you should see the improvement when it's pulled into WebODM.

**Closed by ebrelsford** 2018-05-09 23:55 UTC
